CREATE TABLE IF NOT EXISTS player(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS queue(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS gamesession(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    status INTEGER NOT NULL,
    queue_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS gamesession_players(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    gamesession_id INTEGER NOT NULL,
    player_id INTEGER NOT NULL
);